### ISSUE TITLE
Draft guide feedback

### ISSUE THREAD

**Issue by katheris** [OpenLiberty/draft-guide-microprofile-reactive-messaging#27]
I've stepped through the guide and noticed a few things that were confusing or could be improved.

1. In the "what you'll learn" section you mention "Apache Kafka broker" a couple of times but don't explain what a broker is. May be easier just to say "Apache Kafka".
1. In the async programming section you mention channels but haven't explained what they are yet
1. I noticed that the OrderResource.java, ServingWindowResource.java and pom.xml that we copy and paste are pretty much identical (except for comments) to the ones in the start folder.
1. When I created orders they originally had the status of "NEW" not "IN_PROGRESS" as indicated in the steps
1. There aren't any steps for me to run with my own Kafka, this would be useful I think

In general the guide felt very copy and paste oriented. Would it be possible to ask the participants to add the annotations, rather than having them copy and paste the whole file?

**Comment by lauracowen** [comment]
I've just had a quick look and have some comments in addition to Kate's:

- I think the introduction to this guide is a bit long (it might just be a case of being written more concisely or some of the info removing/moving to later on - I can take a more detailed look if that's useful but not today). Also, I think it'd make more sense to explain what async programming is and why it's important first, before then moving into how MP Reactive Messaging and Kafka contribute to this. Good having a diagram though. :)
- "OpenLiberty" should be two words or the name of the app should consistently be "OpenLibertyCafe".
- Rather than listing all the concepts up-front (under the heading Key Concepts), can they instead each be explained at the point where they're first mentioned (and remove the Key Concepts section)? This isn't meant to be reference documentation but something that take the reader through the ideas that they'd need to be able to create this app.
- "Configuring the MicroProfile Reactive Messaging" This seems to start without any introduction to the section. The first sentence or two needs to summarise the section then lead into the first bit.
- Words like "connectors" are not proper nouns so should not be capitalised.
- "All these properties should be accepted" - "should be"? either they are or they aren't...what can the reader expect to happen?
- Random bullet point in the "Building the Order microservice" section. Also, that bit is introducing the fact that the reader should be updating the pom.xml file - that needs to come before the action, otherwise there's no indication why you're asking the reader to edit the pom.xml file.
- there seem to be a lot of microservices in this single guide - is it necessary to have them create them all like this? Is there any way to simplify this? Is it really critical to understanding what's happening to see so many different services? What specifically does the reader learn from each of the microservices?
- one option would be to tighten the scope of the scenario and just focus on fewer services in the guide then, after testing it all, have a short section in which you suggest things they could do by themselves to extend the app (don't give all the instructions, just set it as a task but have the completed files available to them. in `finish`?). This is something we really should have in the guides anyway to help users practise what they've just learnt.
- @katheris The guide format is to copy the whole file in but then the text following that action highlights the key parts of the code that's been pasted in to explain what the changes are and why they're important. The alternative approach of updating a line at a time often doesn't work very well because it's hard to clearly explain where to put the new line and then the whole app doesn't work (there's nothing to stop the user just doing that instead of copy/pasting the whole file in though). However, I think what you're seeing in terms of a lot of copy/pasting is a symptom of there being so many services in this single guide.

**Comment by katheris** [comment]
@lauracowen ah ok, I see what you mean. I think my previous experience of other OL guides has been with shorter files so it was easier to see what the difference was. Maybe it is worth considering if some of the files could be shortened to make a comparison easier.

**Comment by ankitagrawa** [comment]
**Responses are in BOLD**

**Comment by yeekangc** [comment]
> In the async programming section you mention channels but haven't explained what they are yet
> **It's explained under Key Concepts**
> 
> When I created orders they originally had the status of "NEW" not "IN_PROGRESS" as indicated in the steps
> **In "What is asynchronous programming?" section I have explained that the status goes from NEW->IN_PROGRESS->READY. will add a note for this.**

IMHO, the above is an indication that there are room for improvements still and we should reorganize the content and elaborate where appropriate.

> There aren't any steps for me to run with my own Kafka, this would be useful I think
> **I agree but the whole point of the guide is to focus on reactive messaging and not Kafka. Also don't wanna complicate guide more than what it's now. Developers can always try out different messaging brokers instead of Kafka.**

The above leads me to think that we should further clarify the focus of the guide and provide pointers or indication on what developers should do for this aspect.  (And link out to additional guides for further learning when we have them.)

**Comment by ankitagrawa** [comment]
> In the "what you'll learn" section you mention "Apache Kafka broker" a couple of times but don't explain what a broker is. May be easier just to say "Apache Kafka".

ok
> In the async programming section you mention channels but haven't explained what they are yet

It's explained under key concepts

> I noticed that the OrderResource.java, ServingWindowResource.java and pom.xml that we copy and paste are pretty much identical (except for comments) to the ones in the start folder.

We can reduce some code there

> When I created orders they originally had the status of "NEW" not "IN_PROGRESS" as indicated in the steps

In "What is asynchronous programming?" section I have explained that the status goes from  NEW->IN_PROGRESS->READY.** will add a note for this.

> There aren't any steps for me to run with my own Kafka, this would be useful I think

I agree but the whole point of the guide is to focus on reactive messaging and not Kafka. Also don't wanna complicate guide more than what it's now. Developers can always try out different messaging brokers instead of Kafka.

> In general the guide felt very copy and paste oriented. Would it be possible to ask the participants to add the annotations, rather than having them copy and paste the whole file?

I guess Laura answered this.

@katheris

**Comment by ankitagrawa** [comment]
@lauracowen 

> - I think the introduction to this guide is a bit long (it might just be a case of being written more concisely or some of the info removing/moving to later on - I can take a more detailed look if that's useful but not today). Also, I think it'd make more sense to explain what async programming is and why it's important first, before then moving into how MP Reactive Messaging and Kafka contribute to this. Good having a diagram though. :)

The reason why we have it after reactive messaging and Kafka is because 1) We want to scope this guide to reactive messaging and Kakfa 
 2) In asynchronous we talk about a restaurant scenario which we expand into our application. 
**Do you still think we should move it after messaging and Kafka section?**

> - "OpenLiberty" should be two words or the name of the app should consistently be "OpenLibertyCafe".

I think it's consistent except for this command
"docker build -t openlibertycafe:1.0-SNAPSHOT openLibertyCafe/." 
As per the naming convention, docker image should be lower case and the service name should start with small.

> - Rather than listing all the concepts up-front (under the heading Key Concepts), can they instead each be explained at the point where they're first mentioned (and remove the Key Concepts section)? This isn't meant to be reference documentation but something that take the reader through the ideas that they'd need to be able to create this app.

 That's a great suggestion but I am guessing that would be too difficult and confusing. Moreover there are many concepts which are intertwined and referenced in one class and others might not do it. Also we are using 4 services here. so if we have key concepts upfront people know what's coming. I have seen similar strategy in other guides as well

> - "Configuring the MicroProfile Reactive Messaging" This seems to start without any introduction to the section. The first sentence or two needs to summarise the section then lead into the first bit.

ok will do

> - Words like "connectors" are not proper nouns so should not be capitalised.

ok will do

> - "All these properties should be accepted" - "should be"? either they are or they aren't...what can the reader expect to happen?

I will rephrase it

> - Random bullet point in the "Building the Order microservice" section. Also, that bit is introducing the fact that the reader should be updating the pom.xml file - that needs to come before the action, otherwise there's no indication why you're asking the reader to edit the pom.xml file.

ok will do

> - there seem to be a lot of microservices in this single guide - is it necessary to have them create them all like this? Is there any way to simplify this? Is it really critical to understanding what's happening to see so many different services? What specifically does the reader learn from each of the microservices?

each of the micro services touch difference concepts. We need to have those to explain and make them understand the reactive messaging concept.

> - one option would be to tighten the scope of the scenario and just focus on fewer services in the guide then, after testing it all, have a short section in which you suggest things they could do by themselves to extend the app (don't give all the instructions, just set it as a task but have the completed files available to them. in `finish`?). This is something we really should have in the guides anyway to help users practise what they've just learnt.

while explaining the concepts we need to touch base for all the 4 microservices. Technically there are 6 if we include OpenLibertyCafe and Kafka-zookeper. However from the concept perspective we are just explaining the important ones.

Let me know if you still think otherwise and will make the changes accordingly.

**Comment by yeekangc** [comment]
I am good if we cover key concepts up front.  Sounds like it will be good to reference the concepts in the subsequent sections where relevant too to help the users.

**Comment by gkwan-ibm** [comment]
I suggest to ask readers to read those 4 main concepts from the spec. Add the following before the statement "See MicroProfile Reactive Messaging Specification for more information."  in the "What is MicroProfile Reactive Messaging?" section. "Key Concepts" can be removed from the "Creating a Reactive Messaging application" section.

MicroProfile Reactive Messaging recommends a design to build reactive applications based on the following main concepts:[ Channel](https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_channel), [@Outgoing](https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_message_production_with_outgoing), [@Incoming](https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_message_consumption_with_incoming), [Connectors](https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_connectors).

**Comment by ankitagrawa** [comment]
> I suggest to ask readers to read those 4 main concepts from the spec. Add the following before the statement "See MicroProfile Reactive Messaging Specification for more information." in the "What is MicroProfile Reactive Messaging?" section. "Key Concepts" can be removed from the "Creating a Reactive Messaging application" section.
> 
> MicroProfile Reactive Messaging recommends a design to build reactive applications based on the following main concepts: Channel, @Outgoing, @Incoming, Connectors.

I feel since this is first of the lot. We should give a brief intro. If anyone wants to read more they can always look at the spec. We provide the spec link in what is reactive messaging section at the beginning. 
If we tell them to read from the spec they might get lost since it contains so much data and not all the method signatures are used.

**Comment by lauracowen** [comment]
No, I don't think we shouldn't tell them to go read the spec. As well as getting lost, the audience of the spec is developers who are implementing the spec. The information that is needed by an end-user who is using the feature in OL should be in a combination of guides (concise scenario that explains only what is needed to understand the guide) and the docs (richer introductions to the concepts).

**Comment by ankitagrawa** [comment]
@lauracowen  

> No, I don't think we shouldn't tell them to go read the spec. As well as getting lost, the audience of the spec is developers who are implementing the spec. The information that is needed by an end-user who is using the feature in OL should be in a combination of guides (concise scenario that explains only what is needed to understand the guide) and the docs (richer introductions to the concepts).

so are you suggesting that I should follow Gilberts feedback and make that change?

**Comment by lauracowen** [comment]
No - don't add links to the spec. But yes, provide a brief intro if it's needed.

I'm going to attempt to do a full review of this guide sometime this week. I just need to finish work on some other docs work first.

**Comment by lauracowen** [comment]
No, I don't think we shouldn't tell them to go read the spec. As well as getting lost, the audience of the spec is developers who are implementing the spec. The information that is needed by an end-user who is using the feature in OL should be in a combination of guides (concise scenario that explains only what is needed to understand the guide) and the docs (richer introductions to the concepts).

**Comment by ankitagrawa** [comment]
The application has been changed to System-Inventory and these points don't hold. Closing this issue for now.
